Ajout de la partie admin / blog, des pages d'erreur, amélioration de …
jdevuono54/OCR-P5 pull request #21
Opened 2021-11-20 22:05 UTC by jdevuono54

2021-11-22 23:56 UTC, jdevuono54 commented on public/scripts/main.js
> +        document.addEventListener('keydown', e => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
        document.addEventListener('keydown', (e) => {
```

2021-11-23 18:22 UTC, jdevuono54 commented on public/scripts/main.js
> +        document.addEventListener('keydown', e => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
        document.addEventListener('keydown', (e) => {
```

2021-11-23 18:41 UTC, jdevuono54 commented on public/scripts/main.js
> +    img.style.width = '350px';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
        img.style.width = "350px";
```

2021-11-23 18:41 UTC, jdevuono54 commented on public/scripts/main.js
> +      if (!key.indexOf(input)) return 1;
Codacy has a fix for the issue: [Expected { after 'if' condition.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
      if (!key.indexOf(input)) {return 1;}
```

2021-11-23 18:45 UTC, jdevuono54 commented on public/scripts/main.js
> +    document.addEventListener('keydown', (e) => {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
    document.addEventListener("keydown", (e) => {
```

2021-11-23 19:09 UTC, jdevuono54 commented on public/scripts/main.js
> +    img.style.position = 'fixed';
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
        img.style.position = "fixed";
```

2021-11-23 19:44 UTC, jdevuono54 commented on public/scripts/main.js
> +      if (!key.indexOf(input)) { return 1 };
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
      if (!key.indexOf(input)) { return 1; };
```

2021-11-23 19:44 UTC, jdevuono54 commented on public/scripts/main.js
> +      if (!key.indexOf(input)) { return 1 };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
      if (!key.indexOf(input)) { return 1 }
```

2021-11-23 19:59 UTC, jdevuono54 commented on public/scripts/main.js
> +      if (!key.indexOf(input)) { return 1 }
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/jdevuono54/OCR-P5/pullRequest?prid=8453331)
```suggestion
      if (!key.indexOf(input)) { return 1; }
```

2021-11-27 12:12 UTC, TheGarious requested changes

2021-11-27 13:23 UTC, jdevuono54 commented on composer.json
> +        "php": "^7.4",
174fba360795b482b7e49f6f9b0723fa9532c1fb

2021-11-27 13:23 UTC, merged